# version: "3.8" -- Obsolete now
services:

  # VPN
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/pool/config/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASSWORD}
      - SERVER_REGIONS=US California,US Las Vegas,US Silicon Valley,US West
    ports:
      - 8080:8080 # These are for qBittorrent
      - 6881:6881
      - 6881:6881/udp
      - 8081:8081 # qBittorrent
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    # network_mode: host
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=8081
    # ports:
      # - 8081:8081
    volumes:
      - /mnt/pool/config/qbittorrent:/config
      - /mnt/pool/downloads:/downloads
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    # network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/pool/config/jackett:/config
      - /mnt/pool/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
    ports:
      - 9117:9117

  # nzbget:
  #   container_name: nzbget
  #   image: linuxserver/nzbget:latest
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #   volumes:
  #     - ${ROOT}/downloads:/downloads # download folder
  #     - ${ROOT}/config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/pool/config/sonarr:/config
      - /mnt/pool/TV/:/tv
      - /mnt/pool/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/pool/config/radarr:/config
      - /mnt/pool/Movies/:/movies
      - /mnt/pool/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host # Recommended, don't use default (bridge) mode
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/pool/config/Plex:/config
      - /mnt/pool/TV:/tv
      - /mnt/pool/Movies:/movies
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    network_mode: host
    ports:
      - "9000:9000"
      - "8004:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /mnt/pool/config/Homer/:/www/assets
    user: ${PUID}:${PUID} # default
    environment:
      - INIT_ASSETS=0 # default
    ports:
      - 8083:8080
    restart: unless-stopped

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    volumes:
      - /mnt/pool:/srv
      - /mnt/pool/filebrowser.db:/database.db
    user: "${PUID}:${PUID}"
    ports:
      - "8082:80"
    restart: unless-stopped

volumes:
  portainer_data:
