# version: "3.8" -- Obsolete now
services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  portainer_password:
    container_name: portainer_password
    image: portainer/helper-reset-password
    volumes:
      - portainer_data:/data

  nginx_proxy_manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /mnt/pool/config/nginx:/data
      - /mnt/pool/config/nginx/letsencrypt:/etc/letsencrypt
      - ./_hsts_map.conf:/app/templates/_hsts_map.conf
    restart: unless-stopped

  # VPN
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/pool/config/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=${PIA_USER}
      - OPENVPN_PASSWORD=${PIA_PASSWORD}
      - SERVER_REGIONS=US California,US Las Vegas,US Silicon Valley,US West
    ports:
      - 8080:8080 # These are for qBittorrent
      - 6881:6881
      - 6881:6881/udp
      - 8081:8081 # qBittorrent
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=8081
      # Comment this port section out because we're opening it for the Gluetun container which is the one that actually needs it
      # ports: 
      # - 8081:8081
    volumes:
      - /mnt/pool/config/qbittorrent:/config
      - /mnt/pool/downloads:/downloads
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /mnt/pool/config/jackett:/config
      - /mnt/pool/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9117:9117

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${PUID} # default user id, ~defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /mnt/pool/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/pool/config/sonarr:/config
      - /mnt/pool/TV/:/tv
      - /mnt/pool/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/pool/config/radarr:/config
      - /mnt/pool/Movies/:/movies
      - /mnt/pool/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host # Recommended, don't use default (bridge) mode
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional (if using the default (bridge) network mode)
    volumes:
      - /mnt/pool/config/plex:/config
      - /mnt/pool/TV:/tv
      - /mnt/pool/Movies:/movies
    restart: unless-stopped

  tautulli:
    container_name: tautulli
    image: ghcr.io/tautulli/tautulli
    restart: unless-stopped
    volumes:
      - /mnt/pool/config/tautulli:/config
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    ports:
      - 8181:8181

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /mnt/pool/config/homer/:/www/assets
    user: ${PUID}:${PUID} # default
    environment:
      - INIT_ASSETS=0
    ports:
      - 8083:8080
    restart: unless-stopped

  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    volumes:
      - /mnt/pool:/srv
      - /mnt/pool/filebrowser.db:/database.db
    user: "${PUID}:${PUID}"
    ports:
      - "8082:80"
    restart: unless-stopped

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8084:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /mnt/pool/config/scrutiny:/opt/scrutiny/config
      - /mnt/pool/config/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      # - "/dev/sdc" # Uncomment when parity drive is fixed
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:
