services:
  minecraft_server:
    container_name: minecraft_server
    image: itzg/minecraft-server
    network_mode: service:lazytainer
    environment:
      - EULA=true
      - MEMORY=2G
      - MOTD="Welcome to Nick's Minecraft Server! Yippie!!!"

    volumes:
      - /mnt/pool/config/minecraft/data:/data
    labels:
      - lazytainer.group=minecraft
    depends_on:
      - lazytainer
    env_file:
      - ../.env
  
  lazytainer:
    container_name: minecraft_lazytainer
    image: ghcr.io/vmorganp/lazytainer:master
    environment:
      VERBOSE: false
    ports:
      - 25565:25565
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - lazytainer.group.minecraft.sleepMethod=stop
      - lazytainer.group.minecraft.ports=25565
      - lazytainer.group.minecraft.minPacketThreshold=2 # Start after two incomming packets
      - lazytainer.group.minecraft.inactiveTimeout=600 # 10 minutes, to allow the server to bootstrap. You can probably make this lower later if you want.
    restart: unless-stopped
    network_mode: bridge
