services:
  minecraft_server:
    container_name: minecraft_server
    image: itzg/minecraft-server
    environment:
      - EULA: true
      - VERSION: 1.20.4
      - MEMORY: 2G
      - TZ: ${TZ} # timezone, defined in .env
      - MOTD: "Welcome to Nick's Minecraft Server"

    ports:
      - 25565:25565
    volumes:
      - /mnt/pool/config/minecraft/data:/data
  # lazytainer:
  #   image: ghcr.io/vmorganp/lazytainer:master
  #   environment:
  #     VERBOSE: false
  #   ports:
  #     - 25565:25565
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   labels:
  #     - lazytainer.group.minecraft.sleepMethod=stop
  #     - lazytainer.group.minecraft.ports=25565
  #     - lazytainer.group.minecraft.minPacketThreshold=2 # Start after two incomming packets
  #     - lazytainer.group.minecraft.inactiveTimeout=600 # 10 minutes, to allow the server to bootstrap. You can probably make this lower later if you want.
  #   restart: unless-stopped
  #   network_mode: bridge
  # mc:
  #   image: itzg/minecraft-server
  #   environment:
  #     EULA: TRUE
  #     TYPE: PAPER
  #     MEMORY: 4G
  #   volumes:
  #     - ./data:/data
  #   labels:
  #     - lazytainer.group=minecraft
  #   depends_on:
  #     - lazytainer
  #   network_mode: service:lazytainer
  #   tty: true
  #   stdin_open: true
  #   restart: unless-stopped
